name: .NET 8 Build & Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-docker:
    runs-on: ubuntu-latest

    env:
      SOLUTION_NAME: SlamGame.sln
      DOCKER_IMAGE_NAME: SlamGame

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_NAME }}

    - name: Build
      run: dotnet build ${{ env.SOLUTION_NAME }} --configuration Release --no-restore

    - name: Test
      run: dotnet test ${{ env.SOLUTION_NAME }} --no-build --verbosity normal

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3